# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from rust_core import core
__all__ = [
    "load_wiki_talk",
]

def load_wiki_talk(path: builtins.str) -> core.Hypergraph: ...

