# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing

from rust_core.core import graph

__all__ = [
    "load_wiki_talk",
]

def load_wiki_talk(
    dataset_dir: builtins.str | os.PathLike | pathlib.Path,
    cache_dir: typing.Optional[builtins.str | os.PathLike | pathlib.Path],
) -> graph.Hypergraph: ...
