# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import loader
from . import motifs
from . import triangle
__all__ = [
    "H2",
    "H3",
    "H4",
    "H5",
    "Hypergraph",
    "loader",
    "motifs",
    "triangle",
]

@typing.final
class H2:
    ...

@typing.final
class H3:
    ...

@typing.final
class H4:
    ...

@typing.final
class H5:
    ...

@typing.final
class Hypergraph:
    def __new__(cls) -> Hypergraph: ...
    def add_edge(self, edge: typing.Sequence[builtins.int]) -> None: ...
    def add_h2(self, edge: H2) -> None: ...
    def extends_h2(self, edges: typing.Sequence[H2]) -> None: ...
    def add_h3(self, edge: H3) -> None: ...
    def extends_h3(self, edges: typing.Sequence[H3]) -> None: ...
    def add_h4(self, edge: H4) -> None: ...
    def extends_h4(self, edges: typing.Sequence[H4]) -> None: ...
    def add_h5(self, edge: H5) -> None: ...
    def extends_h5(self, edges: typing.Sequence[H5]) -> None: ...

