# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "bfs",
    "common_neighbors_sorted_list",
    "degeneracy_ordering",
    "degeneracy_ordering_py",
    "degree_ordering",
    "sort_adj_list",
]

def bfs(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> builtins.list[builtins.int]: ...

def common_neighbors_sorted_list(a: typing.Sequence[builtins.int], b: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]: ...

def degeneracy_ordering(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.int]: ...

def degeneracy_ordering_py(adj: list) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.int]: ...

def degree_ordering(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int], builtins.int]: ...

def sort_adj_list(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> builtins.list[builtins.list[builtins.int]]: ...

