pub mod motifs3;
pub mod orca;

pub struct EnumerationStats {
    /// Number of connected and disconnected motifs enumerated
    pub total_count: usize,
    /// Number of connected motifs enumerated
    pub connected_count: usize,
    /// Number of connected motifs enumerated
    pub distinct_fingerprints: usize,
    /// Number of connected motifs enumerated
    pub elapsed_time: Duration,
    /// Number of fingerprints that can be generated by 2 or more motifs that are NOT isomorph.
    /// Should be 0 if the fingerprint invariant used is perfect
    pub clashing_buckets_count: usize,
}
