# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "cetc",
    "cetc_s",
]

def cetc(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> builtins.int: ...

def cetc_s(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> builtins.int: ...

