use rust_core_macros::remove_attr;
use std::time::Duration;

#[cfg(feature = "bindings")]
use pyo3::prelude::*;
#[cfg(feature = "bindings")]
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

#[cfg(feature = "bindings")]
#[pyo3::pymodule(submodule)]
pub mod types {
    use pyo3::{pyclass, pymethods};
    use pyo3_stub_gen::derive::gen_stub_pyclass;
    use std::time::Duration;

    #[pymodule_export]
    use super::EnumerationStats;

    #[pymodule_export]
    use super::MotifStats;

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint3;

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint4;

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint5;
}

#[derive(Default, Clone)]
#[cfg_attr(
    feature = "bindings",
    gen_stub_pyclass(module = "rust_core._core.motifs.types"),
    pyclass(from_py_object, str)
)]
#[cfg_attr(not(feature = "bindings"), remove_attr("pyo3"))]
pub struct EnumerationStats {
    /// Number of connected and disconnected motifs enumerated
    #[pyo3(get, set)]
    pub total_count: usize,
    /// Number of connected motifs enumerated
    #[pyo3(get, set)]
    pub connected_count: usize,
    /// Number of connected motifs enumerated
    #[pyo3(get, set)]
    pub distinct_fingerprints: usize,
    /// Number of connected motifs enumerated
    #[pyo3(get, set)]
    pub elapsed_time: Duration,
    /// Number of fingerprints that can be generated by 2 or more motifs that are NOT isomorph.
    /// Should be 0 if the fingerprint invariant used is perfect
    #[pyo3(get, set)]
    pub clashing_buckets_count: usize,
}

#[cfg_attr(feature = "bindings", pymethods)]
#[cfg_attr(not(feature = "bindings"), remove_attr("staticmethod"))]
impl EnumerationStats {
    #[staticmethod]
    pub fn new() -> Self {
        Self::default()
    }
}

#[derive(Default, Clone)]
#[cfg_attr(
    feature = "bindings",
    gen_stub_pyclass(module = "rust_core._core.motifs.types"),
    pyclass(from_py_object, str)
)]
#[cfg_attr(not(feature = "bindings"), remove_attr("pyo3"))]
/// A struct containing information about the distribution of a given motif inside a hypergraph
pub struct MotifStats {
    /// Number of distinct motifs subgraphs isomorphic to the given motif
    #[pyo3(get, set)]
    pub count: usize,
    /// The mean intensity, i.e. the mean intensity between all intances of the motif. Useful
    /// in weighted hypergraphs
    #[pyo3(get, set)]
    pub mean_intensity: f64,
    /// The mean coherence, i.e. the mean coherence between all intances of the motif. Useful
    /// in weighted hypergraphs
    #[pyo3(get, set)]
    pub mean_coherence: f64,

    /// The mean actual_intensity, i.e. the mean actual_intensity between all intances of the motif. Useful
    /// in weighted hypergraphs
    #[pyo3(get, set)]
    pub actual_intensity: f64,
}

#[cfg_attr(feature = "bindings", pymethods)]
#[cfg_attr(not(feature = "bindings"), remove_attr("staticmethod"))]
impl MotifStats {
    #[staticmethod]
    pub fn new() -> Self {
        Self::default()
    }
}

impl std::fmt::Display for EnumerationStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Total motifs:          {}\n\
             Connected motifs:      {}\n\
             Distinct fingerprints: {}\n\
             Elapsed time:          {:?}\n\
             Clashing buckets:      {}",
            self.total_count,
            self.connected_count,
            self.distinct_fingerprints,
            self.elapsed_time,
            self.clashing_buckets_count
        )
    }
}

impl std::fmt::Display for MotifStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Count:          {}\n\
             Mean intensity: {}\n\
             Mean coherence: {:?}\n\
             Actual intensity: {}",
            self.count, self.mean_intensity, self.mean_coherence, self.actual_intensity
        )
    }
}
impl std::fmt::Debug for MotifStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "{}", self)
    }
}
