use pyo3::pymodule;
pub use types::*;

#[pymodule]
pub mod types {
    use pyo3::{pyclass, pymethods};
    use pyo3_stub_gen::derive::gen_stub_pyclass;
    use std::time::Duration;

    #[gen_stub_pyclass(module = "rust_core._core.motifs.types")]
    #[pyclass(from_py_object, str)]
    #[derive(Default, Clone)]
    pub struct EnumerationStats {
        /// Number of connected and disconnected motifs enumerated
        pub total_count: usize,
        /// Number of connected motifs enumerated
        pub connected_count: usize,
        /// Number of connected motifs enumerated
        pub distinct_fingerprints: usize,
        /// Number of connected motifs enumerated
        pub elapsed_time: Duration,
        /// Number of fingerprints that can be generated by 2 or more motifs that are NOT isomorph.
        /// Should be 0 if the fingerprint invariant used is perfect
        pub clashing_buckets_count: usize,
    }
    #[pymethods]
    impl EnumerationStats {
        #[staticmethod]
        pub fn new() -> Self {
            Self::default()
        }
    }

    /// A struct containing information about the distribution of a given motif inside a hypergraph
    #[gen_stub_pyclass(module = "rust_core._core.motifs.types")]
    #[pyclass(from_py_object, str)]
    #[derive(Default, Clone)]
    pub struct MotifStats {
        /// Number of distinct motifs subgraphs isomorphic to the given motif
        pub count: usize,
        /// The mean intensity, i.e. the mean intensity between all intances of the motif. Useful
        /// in weighted hypergraphs
        pub mean_intensity: f64,
        /// The mean coherence, i.e. the mean coherence between all intances of the motif. Useful
        /// in weighted hypergraphs
        pub mean_coherence: Duration,

        /// The mean actual_intensity, i.e. the mean actual_intensity between all intances of the motif. Useful
        /// in weighted hypergraphs
        pub actual_intensity: f64,
    }

    #[pymethods]
    impl MotifStats {
        #[staticmethod]
        pub fn new() -> Self {
            Self::default()
        }
    }

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint3;

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint4;

    #[pymodule_export]
    use crate::motifs::fingerprint::Fingerprint5;
}

impl std::fmt::Display for EnumerationStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Total motifs:          {}\n\
             Connected motifs:      {}\n\
             Distinct fingerprints: {}\n\
             Elapsed time:          {:?}\n\
             Clashing buckets:      {}",
            self.total_count,
            self.connected_count,
            self.distinct_fingerprints,
            self.elapsed_time,
            self.clashing_buckets_count
        )
    }
}

impl std::fmt::Display for MotifStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Count:          {}\n\
             Mean intensity: {}\n\
             Mean coherence: {:?}\n\
             Actual intensity: {}",
            self.count, self.mean_intensity, self.mean_coherence, self.actual_intensity
        )
    }
}
