# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "forward",
    "forward_hashed",
    "forward_hbs",
]

def forward(adj: typing.Sequence[typing.Sequence[builtins.int]], sort_degrees: builtins.bool) -> builtins.int: ...

def forward_hashed(adj: typing.Sequence[typing.Sequence[builtins.int]], sort_degrees: builtins.bool) -> builtins.int: ...

def forward_hbs(adj: typing.Sequence[typing.Sequence[builtins.int]], sort_degrees: builtins.bool) -> builtins.int: ...

