# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "compact_forward",
    "forward",
]

def compact_forward(adj: typing.Sequence[typing.Sequence[builtins.int]], sort_degrees: builtins.bool) -> builtins.int: ...

def forward(adj: typing.Sequence[typing.Sequence[builtins.int]], sort_degrees: builtins.bool) -> builtins.int: ...

