# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "kclist",
    "kclist_py",
]

def kclist(adj: typing.Sequence[typing.Sequence[builtins.int]]) -> builtins.int: ...

def kclist_py(adj: list) -> builtins.int: ...

