# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "count_motifs_3",
    "count_motifs_4",
    "orca",
]

def count_motifs_3(edges: tuple[typing.Sequence[tuple[builtins.int, builtins.int]], typing.Sequence[tuple[builtins.int, builtins.int, builtins.int]]]) -> None: ...

def count_motifs_4(edges: tuple[typing.Sequence[tuple[builtins.int, builtins.int]], typing.Sequence[tuple[builtins.int, builtins.int, builtins.int]], typing.Sequence[tuple[builtins.int, builtins.int, builtins.int, builtins.int]]]) -> None: ...

def orca() -> None: ...

