# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "count_motifs_3",
    "orca",
]

def count_motifs_3() -> None: ...

def orca() -> None: ...

